### ISSUE TITLE
executing sapphire v1.0.1 and first contact with user....

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#21]
1) Initialization of the .exe takes about 1 minute on my AMD FX™-8320 Eight Core Processor 3,51 GHZ with 8 GB internal memory W8.1 pro 64-bits., x64 processor. Through task manager it takes about 110 MB internal memory divided in 2 background processes.

2) It checks my wallet which is encrypted. After they congrats me they say to write my password down now. Which password? The one I have or miss I something? What then to write down? 

3) I continue and get warned that it can takes some time? 
a) Should you not specify why it takes time and which key factors influences the speed and what are average times processing? 
b) Should you also not mention how many times in the future it will take that much time etc.? 
c) Should you not also mention that you cannot use until it is finished sync. or …etc.?
d) again, should you not mention that it not only takes time but also absorbs space on your drive or...?
e) can you intterupt installation processing and what happens then? do you need to start over etc?

4) Finished. 100% sync now. It took about 1h for 10%, about 7h for 70% and guess therefore around 10h total? The space in the eccoin folder is about 3,5 GB (including the bootstrap.dat.old file).

**Comment by csmartinsfct** [comment]
1. We are looking into alternatives to check for running processes, it's not machine dependent, the library is just slow-ish. The process of loading takes around 20 seconds or so? 

2. The one you have, yes. So you don't lose it.

3. a) I suppose I can throw an estimation, not entirely easy since for some users it can take days, some 15 hours. But I'll try to word it better.
 b) yes
 c) yes
 d) yes
 e) yes you can, it resumes.

4. that's actually a pretty impressive number.
